services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - ./src/.env